Added support for using shasum and openssl to calculate checksums

diff --git a/inline-checksum b/inline-checksum
--- a/inline-checksum
+++ b/inline-checksum
@@ -51,6 +51,7 @@
 # 2: Error During Argument Parsing      #
 # 3: Missing Dependency                 #
 # 4: Unable to Make Temporary File      #
+# 5: Unknown Error During Checksum Calc #
 # ------------------------------------- #
 
 _program_name="$(basename "${0}")"
@@ -153,20 +154,36 @@ main() {
 			shift 1
 			case "${algorithm}" in
 			sha256)
-				if ! command -v sha256sum >/dev/null 2>&1; then
-					printf "[%s]: %s: sha256sum must be installed to check sha256 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
+				if command -v sha256sum >/dev/null 2>&1; then
+					true
+				elif command -v shasum >/dev/null 2>&1; then
+					true
+				elif command -v openssl >/dev/null 2>&1; then
+					true
+				else
+					printf "[%s]: %s: sha256sum or an equivalent must be installed to check sha256 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
 					return 3
 				fi
 				;;
 			sha512)
-				if ! command -v sha512sum >/dev/null 2>&1; then
-					printf "[%s]: %s: sha512sum must be installed to check sha512 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
+				if command -v sha512sum >/dev/null 2>&1; then
+					true
+				elif command -v shasum >/dev/null 2>&1; then
+					true
+				elif command -v openssl >/dev/null 2>&1; then
+					true
+				else
+					printf "[%s]: %s: sha512sum or an equivalent must be installed to check sha512 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
 					return 3
 				fi
 				;;
 			md5)
-				if ! command -v md5sum >/dev/null 2>&1; then
-					printf "[%s]: %s: md5sum must be installed to check md5 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
+				if command -v md5sum >/dev/null 2>&1; then
+					true
+				elif command -v openssl >/dev/null 2>&1; then
+					true
+				else
+					printf "[%s]: %s: md5sum or an equivalent must be installed to check md5 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
 					return 3
 				fi
 				;;
@@ -228,16 +245,38 @@ main() {
 	fi
 	case "${algorithm}" in
 	sha256)
-		printf "%s  %s" "${provided_hash}" "${target_file}" | sha256sum -c - >/dev/null 2>&1
-		status="${?}"
+		if command -v sha256sum >/dev/null 2>&1; then
+			hash=$(sha256sum "${target_file}" | cut -f 1 -d " ")
+		elif command -v shasum >/dev/null 2>&1; then
+			hash=$(shasum -a 256 "${target_file}" | cut -f 1 -d " ")
+		elif command -v openssl >/dev/null 2>&1; then
+			hash=$(openssl sha256 "${target_file}" | cut -f 2 -d " ")
+		else
+			printf "[%s]: %s: Unable to calculate checksum using algorithm '%s'.\n" "$(date +'%H:%M:%S')" "${_program_name}" "${algorithm}" >&2
+			return 5
+		fi
 		;;
 	sha512)
-		printf "%s  %s" "${provided_hash}" "${target_file}" | sha512sum -c - >/dev/null 2>&1
-		status="${?}"
+		if command -v sha512sum >/dev/null 2>&1; then
+			hash=$(sha512sum "${target_file}" | cut -f 1 -d " ")
+		elif command -v shasum >/dev/null 2>&1; then
+			hash=$(shasum -a 512 "${target_file}" | cut -f 1 -d " ")
+		elif command -v openssl >/dev/null 2>&1; then
+			hash=$(openssl sha512 "${target_file}" | cut -f 2 -d " ")
+		else
+			printf "[%s]: %s: Unable to calculate checksum using algorithm '%s'.\n" "$(date +'%H:%M:%S')" "${_program_name}" "${algorithm}" >&2
+			return 5
+		fi
 		;;
 	md5)
-		printf "%s  %s" "${provided_hash}" "${target_file}" | md5sum -c - >/dev/null 2>&1
-		status="${?}"
+		if command -v md5sum >/dev/null 2>&1; then
+			hash=$(md5sum "${target_file}" | cut -f 1 -d " ")
+		elif command -v openssl >/dev/null 2>&1; then
+			hash=$(openssl md5 "${target_file}" | cut -f 2 -d " ")
+		else
+			printf "[%s]: %s: Unable to calculate checksum using algorithm '%s'.\n" "$(date +'%H:%M:%S')" "${_program_name}" "${algorithm}" >&2
+			return 5
+		fi
 		;;
 	*)
 		printf "[%s]: %s: Invalid algorithm '%s' was specified. One of 'sha256', 'sha512', or 'md5' must be provided.\n" "$(date +'%H:%M:%S')" "${_program_name}" "${algorithm}" >&2
@@ -248,7 +287,7 @@ main() {
 	# ------------------------------------------------ #
 	# Compare Calculated Checksum to Provided Checksum #
 	# ------------------------------------------------ #
-	if [ "${status}" -ne 0 ]; then
+	if [ "${hash}" -ne "${provided_hash}" ]; then
 		printf "[%s]: %s: checksum for target file '%s' does not match provided checksum '%s' using algorithm '%s'.\n" "$(date +'%H:%M:%S')" "${_program_name}" "${target_file}" "${provided_hash}" "${algorithm}" >&2
 		return 1
 	fi
