Added support for combining flags like -xa to be POSIX compliant

diff --git a/inline-checksum b/inline-checksum
--- a/inline-checksum
+++ b/inline-checksum
@@ -102,6 +102,33 @@ main() {
 			version
 			shift 1
 			return 0
+		elif printf "%s" "${1}" | grep -q -E -- "^-xa" 2>/dev/null; then
+			output_file_name="1"
+			case "${1}" in
+			*=*)
+				leader="${1%%=*}="
+				algorithm="${1#"${leader}"}"
+				;;
+			-xa*)
+				algorithm="${1#-xa}"
+				;;
+			*)
+				printf "[%s]: %s: invalid algorithm format -- '%s\n'" "$(date +'%H:%M:%S')" "${_program_name}" "${1}" >&2
+				return 2
+				;;
+			esac
+			if [ -z "${algorithm}" ]; then
+				if [ -n "${2}" ]; then
+					case "${2}" in
+					-*) ;;
+					*)
+						algorithm="${2}"
+						shift 1
+						;;
+					esac
+				fi
+			fi
+			shift 1
 		elif printf "%s" "${1}" | grep -q -E -- "(-a)|(--a(l(g(o(r(i(t(h(m)?)?)?)?)?)?)?)?)" 2>/dev/null; then
 			case "${1}" in
 			*=*)
@@ -155,46 +182,6 @@ main() {
 				fi
 			fi
 			shift 1
-			case "${algorithm}" in
-			sha256)
-				if command -v sha256sum >/dev/null 2>&1; then
-					true
-				elif command -v shasum >/dev/null 2>&1; then
-					true
-				elif command -v openssl >/dev/null 2>&1; then
-					true
-				else
-					printf "[%s]: %s: sha256sum or an equivalent must be installed to check sha256 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
-					return 3
-				fi
-				;;
-			sha512)
-				if command -v sha512sum >/dev/null 2>&1; then
-					true
-				elif command -v shasum >/dev/null 2>&1; then
-					true
-				elif command -v openssl >/dev/null 2>&1; then
-					true
-				else
-					printf "[%s]: %s: sha512sum or an equivalent must be installed to check sha512 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
-					return 3
-				fi
-				;;
-			md5)
-				if command -v md5sum >/dev/null 2>&1; then
-					true
-				elif command -v openssl >/dev/null 2>&1; then
-					true
-				else
-					printf "[%s]: %s: md5sum or an equivalent must be installed to check md5 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
-					return 3
-				fi
-				;;
-			*)
-				printf "[%s]: %s: If '--algorithm' is specified, one of 'sha256', 'sha512', or 'md5' must be provided.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
-				return 2
-				;;
-			esac
 		elif printf "%s" "${1}" | grep -q -E -- "(-x)|(--o(u(t(p(u(t(-(f(i(l(e(n(a(m(e)?)?)?)?)?)?)?)?)?)?)?)?)?)?)" 2>/dev/null; then
 			output_file_name="1"
 			shift 1
@@ -217,6 +204,50 @@ main() {
 		return 2
 	fi
 	provided_hash="${1}"
+
+	# -------------------------- #
+	# Validate Algorithm Backend #
+	# -------------------------- #
+	case "${algorithm}" in
+	sha256)
+		if command -v sha256sum >/dev/null 2>&1; then
+			true
+		elif command -v shasum >/dev/null 2>&1; then
+			true
+		elif command -v openssl >/dev/null 2>&1; then
+			true
+		else
+			printf "[%s]: %s: sha256sum or an equivalent must be installed to check sha256 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
+			return 3
+		fi
+		;;
+	sha512)
+		if command -v sha512sum >/dev/null 2>&1; then
+			true
+		elif command -v shasum >/dev/null 2>&1; then
+			true
+		elif command -v openssl >/dev/null 2>&1; then
+			true
+		else
+			printf "[%s]: %s: sha512sum or an equivalent must be installed to check sha512 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
+			return 3
+		fi
+		;;
+	md5)
+		if command -v md5sum >/dev/null 2>&1; then
+			true
+		elif command -v openssl >/dev/null 2>&1; then
+			true
+		else
+			printf "[%s]: %s: md5sum or an equivalent must be installed to check md5 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
+			return 3
+		fi
+		;;
+	*)
+		printf "[%s]: %s: If '--algorithm' is specified, one of 'sha256', 'sha512', or 'md5' must be provided.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
+		return 2
+		;;
+	esac
 
 	# -------------------------- #
 	# Parse Target File or Stdin #
@@ -244,13 +275,7 @@ main() {
 	# ---------------------------------- #
 	# Calculate Checksum for Target File #
 	# ---------------------------------- #
-	if [ -z "${algorithm}" ]; then
-		algorithm="sha256"
-		if ! sha256sum --version >/dev/null 2>&1; then
-			printf "[%s]: %s: sha256sum must be installed to check sha256 hashes.\n" "$(date +'%H:%M:%S')" "${_program_name}" >&2
-			return 3
-		fi
-	fi
+	algorithm="${algorithm:-sha256}"
 	case "${algorithm}" in
 	sha256)
 		if command -v sha256sum >/dev/null 2>&1; then
